# Generated by Django 3.2 on 2021-07-06 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_app', '0017_auto_20210320_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 17, 44, 55, 931211), help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
